### ISSUE TITLE
run_qa.py 파일에서 argument로 받지 않은 변수를 참조합니다.

### ISSUE THREAD

**Issue by vanang** [enlipleai/kor_pratrain_LM#5]
run_qa.py로 korquad 학습중에 아래와 같은 에러가 발생하는데요.

원인을 보니, args.gradient_accumulation_steps 가 main에서 인자로 받은않은 파라미터로 보입니다.

```Bash
Traceback (most recent call last):
  File "run_qa.py", line 280, in <module>
    main()
  File "run_qa.py", line 276, in main
    train(args, train_dataset, model)
  File "run_qa.py", line 46, in train
    t_total = len(train_dataloader) // args.gradient_accumulation_steps * args.num_train_epochs
AttributeError: 'Namespace' object has no attribute 'gradient_accumulation_steps'
```

우선 임시방편으로, run_classifier.py에서 아래 코드를 발췌하여 붙여넣기 하면 될듯합니다.

```Python
 parser.add_argument('--gradient_accumulation_steps',
                        type=int,
                        default=1,
                        help="Number of updates steps to accumulate before performing a backward/update pass.")
```
코드 수정 부탁드립니다.

**Comment by jeonsworld** [comment]
감사합니다. 해당부분 수정하였습니다.

**Comment by vanang** [comment]
run_qa.py에서 args.weight_decay도 위와 같은 문제가 있습니다.

일단 0.01로 해당부분을 수정하여 사용은 하고 있습니다.

전체적으로 Review 후 수정해주심이 좋을 듯 하네요.
